/*
 * Eeprom.h
 *
 * Created: 29.08.2016 17:39:28
 *  Author: pieru
 */ 


#ifndef EEPROM_H_
#define EEPROM_H_


#define EEPROM_OFFSET				0
#define EEPROM_PROTOCOL_VERSION		2
#define EEPROM_MODE					1

#define EEPROM_OFFSET_PID_MANAGER	100

#define EPR_MAGIC_uint8_t              0
#define EPR_BAUDRATE				1	//4bajty
#define EPR_INTEGRITY_uint8_t			5   //1bajt Here the xored sum over eeprom is stored
#define EPR_VERSION					6   //1bajt Version id for updates in EEPROM storage

//***************************************
#define EEPROM_EXT0_START			0
#define EPR_EXT0_HEAT_MANAGER		EEPROM_EXT0_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT0_ANALOG_PIN			EEPROM_EXT0_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT0_DRIVE_MAX			EEPROM_EXT0_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT0_PID_PGAIN			EEPROM_EXT0_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_EXT0_PID_IGAIN			EEPROM_EXT0_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_EXT0_PID_DGAIN			EEPROM_EXT0_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_EXT0_PID_MAX			EEPROM_EXT0_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT0_DRIVE_MIN			EEPROM_EXT0_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT0_TYPE_SENSOR		EEPROM_EXT0_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT0_COOLER_SPEED		EEPROM_EXT0_START+19+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_EXT0_COUNT			19	//suma bajtow zajmowana przez zmienne dotyczace EXT0

//***************************************
#define EEPROM_EXT1_START			EEPROM_EXT0_COUNT+1
#define EPR_EXT1_HEAT_MANAGER		EEPROM_EXT1_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT1_ANALOG_PIN			EEPROM_EXT1_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT1_DRIVE_MAX			EEPROM_EXT1_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT1_PID_PGAIN			EEPROM_EXT1_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_EXT1_PID_IGAIN			EEPROM_EXT1_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_EXT1_PID_DGAIN			EEPROM_EXT1_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_EXT1_PID_MAX			EEPROM_EXT1_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT1_DRIVE_MIN			EEPROM_EXT1_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT1_TYPE_SENSOR		EEPROM_EXT1_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_EXT1_COOLER_SPEED		EEPROM_EXT1_START+19+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_EXT1_COUNT			19	//suma bajtow zajmowana przez zmienne dotyczace EXT1

//***************************************
#define EEPROM_BED0_START			EEPROM_EXT1_START+EEPROM_EXT1_COUNT+1
#define EPR_BED0_HEAT_MANAGER		EEPROM_BED0_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED0_ANALOG_PIN			EEPROM_BED0_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED0_DRIVE_MAX			EEPROM_BED0_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED0_PID_PGAIN			EEPROM_BED0_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED0_PID_IGAIN			EEPROM_BED0_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED0_PID_DGAIN			EEPROM_BED0_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED0_PID_MAX			EEPROM_BED0_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED0_DRIVE_MIN			EEPROM_BED0_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED0_TYPE_SENSOR		EEPROM_BED0_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_BED0_COUNT			18	//suma bajtow zajmowana przez zmienne dotyczace BED0

//***************************************
#define EEPROM_BED1_START			EEPROM_BED0_START+EEPROM_BED0_COUNT+1
#define EPR_BED1_HEAT_MANAGER		EEPROM_BED1_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED1_ANALOG_PIN			EEPROM_BED1_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED1_DRIVE_MAX			EEPROM_BED1_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED1_PID_PGAIN			EEPROM_BED1_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED1_PID_IGAIN			EEPROM_BED1_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED1_PID_DGAIN			EEPROM_BED1_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED1_PID_MAX			EEPROM_BED1_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED1_DRIVE_MIN			EEPROM_BED1_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED1_TYPE_SENSOR		EEPROM_BED1_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_BED1_COUNT			18	//suma bajtow zajmowana przez zmienne dotyczace BED1

//***************************************
#define EEPROM_BED2_START			EEPROM_BED1_START+EEPROM_BED1_COUNT+1
#define EPR_BED2_HEAT_MANAGER		EEPROM_BED2_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED2_ANALOG_PIN			EEPROM_BED2_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED2_DRIVE_MAX			EEPROM_BED2_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED2_PID_PGAIN			EEPROM_BED2_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED2_PID_IGAIN			EEPROM_BED2_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED2_PID_DGAIN			EEPROM_BED2_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED2_PID_MAX			EEPROM_BED2_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED2_DRIVE_MIN			EEPROM_BED2_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED2_TYPE_SENSOR		EEPROM_BED2_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_BED2_COUNT			18	//suma bajtow zajmowana przez zmienne dotyczace BED2

//***************************************
#define EEPROM_BED3_START			EEPROM_BED2_START+EEPROM_BED2_COUNT+1
#define EPR_BED3_HEAT_MANAGER		EEPROM_BED3_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED3_ANALOG_PIN			EEPROM_BED3_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED3_DRIVE_MAX			EEPROM_BED3_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED3_PID_PGAIN			EEPROM_BED3_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED3_PID_IGAIN			EEPROM_BED3_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED3_PID_DGAIN			EEPROM_BED3_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_BED3_PID_MAX			EEPROM_BED3_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED3_DRIVE_MIN			EEPROM_BED3_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_BED3_TYPE_SENSOR		EEPROM_BED3_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_BED3_COUNT			18	//suma bajtow zajmowana przez zmienne dotyczace BED3

//***************************************
#define EEPROM_CHAMB0_START			EEPROM_BED3_START+EEPROM_BED3_COUNT+1
#define EPR_CHAMB0_HEAT_MANAGER		EEPROM_CHAMB0_START+1+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_CHAMB0_ANALOG_PIN		EEPROM_CHAMB0_START+2+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_CHAMB0_DRIVE_MAX		EEPROM_CHAMB0_START+3+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_CHAMB0_PID_PGAIN		EEPROM_CHAMB0_START+4+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_CHAMB0_PID_IGAIN		EEPROM_CHAMB0_START+8+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_CHAMB0_PID_DGAIN		EEPROM_CHAMB0_START+12+EEPROM_OFFSET_PID_MANAGER //4bajty
#define EPR_CHAMB0_PID_MAX			EEPROM_CHAMB0_START+16+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_CHAMB0_DRIVE_MIN		EEPROM_CHAMB0_START+17+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_CHAMB0_TYPE_SENSOR		EEPROM_CHAMB0_START+18+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EPR_CHAMB0_COOLER_SPEED		EEPROM_CHAMB0_START+19+EEPROM_OFFSET_PID_MANAGER //1bajt
#define EEPROM_CHAMB0_COUNT			19  //suma bajtow zajmowana przez zmienne dotyczace CHAMB0
//***************************************

void eprSetuint8_t(unsigned int pos,uint8_t value);
void eprSetInt16(unsigned int pos,int16_t value);
void eprSetInt32(unsigned int pos,int32_t value);
void eprSetFloat(unsigned int pos,float value);
uint8_t eprGetuint8_t(unsigned int pos);
int16_t eprGetInt16(unsigned int pos);
int32_t eprGetInt32(unsigned int pos);
float eprGetFloat(unsigned int pos);

void initBaudrate();

uint8_t get_epr_version();
void readDataFromEEPROM();
void restoreEEPROMSettingsFromConfiguration();
void load_default_variables();
void storeDataIntoEEPROM();

#endif /* EEPROM_H_ */